#!/usr/bin/ruby

# For an OO language, this is distinctly procedural. Should probably fix that.
require 'json'

details = Hash.new({})

capture_params = [
  { :name => "title", :message => "DESK - Discrete Event Simulation Kit" },
  { :name => "url", :message => "https://github.com/joaoflavioufmg/desk" },
  { :name => "description", :message => "DESK (Discrete Event Simulation Kit) is an open-source Python framework for discrete-event simulation with support for replication analysis, factorial experiments, validation, visualization, and input distribution fitting." },
  { :name => "license", :message => "GPL-3.0-only" },
  { :name => "doi", :message => "10.5281/zenodo.18088013" },
  { :name => "keywords", :message => "discrete-event simulation, simulation, operations research, experiment design, replication analysis, simpy, open source" },
  { :name => "version", :message => "v1.1.4" }
]

puts "I'm going to try and help you prepare some things for your JOSS submission"
puts "If all goes well then we'll have a nice codemeta.json file soon..."
puts ""
puts "************************************"
puts "*    First, some basic details     *"
puts "************************************"
puts ""

# Loop through the desired captures and print out for clarity
capture_params.each do |param|
  puts param[:message]
  print "> "
  input = gets

  details[param[:name]] = input.chomp

  puts ""
  puts "OK, your project has #{param[:name]}: #{input}"
  puts ""
end

puts ""
puts "************************************"
puts "*        Experimental stuff        *"
puts "************************************"
puts ""

puts "Would you like me to try and build a list of authors for you?"
puts "(You need to be running this script in a git repository for this to work)"
print "> (Y/N)"
answer = gets.chomp

case answer.downcase
when "y", "yes"

  # Use git shortlog to extract a list of author names and commit counts.
  # Note we don't extract emails here as there's often different emails for
  # each user. Instead we capture emails at the end.

  git_log = `git shortlog --summary --numbered --no-merges`

  # ["252\tMichael Jackson", "151\tMC Hammer"]
  authors_and_counts = git_log.split("\n").map(&:strip)

  authors_and_counts.each do |author_count|
    count, author = author_count.split("\t").map(&:strip)

    puts "Looks like #{author} made #{count} commits"
    puts "Add them to the output?"
    print "> (Y/N)"
    answer = gets.chomp

    # If a user chooses to add this author to the output then we ask for some
    # additional information including their email, ORCID and affiliation.
    case answer.downcase
    when "y", "yes"
      puts "What is #{author}'s email address? (hit enter to skip)"
      print "> "
      email = gets.chomp

      puts "What is #{author}'s ORCID? (hit enter to skip)"
      puts "For example: http://orcid.org/0000-0000-0000-0000"
      print "> "
      orcid = gets.chomp

      puts "What is #{author}'s affiliation? (hit enter to skip)"
      print "> "
      affiliation = gets.chomp


      details['authors'].merge!(author => { 'commits' => count,
                                            'email' => email,
                                            'orcid' => orcid,
                                            'affiliation' => affiliation })

    when "n", "no"
      puts "OK boss..."
      puts ""
    end
  end
when "n", "no"
  puts "OK boss..."
  puts ""
end

puts "Reticulating splines"

5.times do
  print "."
  sleep 0.5
end

puts ""
puts "Generating some JSON goodness..."

# TODO: work out how to use some kind of JSON template here.
# Build the output list of authors from the inputs we've collected.
output_authors = []

details['authors'].each do |author_name, values|
  entry = {
    "@id" => values['orcid'],
    "@type" => "Person",
    "email" => values['email'],
    "name" => author_name,
    "affiliation" => values['affiliation']
  }
  output_authors << entry
end

# TODO: this is currently a static template (written out here). It would be good
# to do something smarter here.
output = {
  "@context" => "https://raw.githubusercontent.com/codemeta/codemeta/master/codemeta.jsonld",
  "@type": "SoftwareSourceCode",
  "programmingLanguage": "Python",
  "runtimePlatform": "Python >=3.10",
  "relatedLink": [
  "https://desk-sim.readthedocs.io",
  "https://github.com/joaoflavioufmg/desk"],
  "issueTracker": "https://github.com/joaoflavioufmg/desk/issues",
  "readme": "https://raw.githubusercontent.com/joaoflavioufmg/desk/main/README.md",
  "author" => output_authors,
  "identifier" => details['doi'],
  "codeRepository" => details['url'],
  "datePublished" => "2025-12-29",
  "dateModified" => "2025-12-29",
  "dateCreated" => "2025-10-12",
  "description" => details['description'],
  "keywords" => details['keywords'],
  "license" => details['license'],
  "title" => details['title'],
  "version" => details['version']
}

File.open('codemeta.json', 'w') {|f| f.write(JSON.pretty_generate(output)) }
